// This file is autogenerated, do not edit here

public class AVImageConstants {
    static let imageNames: [String] = [
        "fire",
        "Winner Punya Orang",
    ]
    static let imagePaths: [String] = [
"./Assets.xcassets/fire.imageset",
"./Assets.xcassets/Winner Punya Orang.imageset",
    ]
    static let unusedAssets: [String] = [
    ]
}
